name: FlagsCore
version: 1.0.3
description: Module that adds general flags to the Flags plugin.
author: Alshain01
website: http://dev.bukkit.org/bukkit-plugins/flags/
main: io.github.alshain01.FlagsCore.FlagsCore
depend: [Flags]
